name: weaather_flutter_app
description: An weather app build with flutter framework

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

# http client
  dio: ^4.0.6

# injecao de dependencia
  get_it: ^7.2.0

# salvar dados locais
  hive: ^2.0.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

# state managment
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
# gerar codigos por modulo
  build_runner: ^2.2.0

# gerar os adapter
  hive_generator: ^1.0.1

# gerar statemanagment
  mobx_codegen: ^2.0.6

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
